### ISSUE TITLE
Possibility of row_percent getting zero and terminating to an error

### ISSUE THREAD

**Issue by shreydiverta** [imneonizer/How-to-find-if-an-image-is-bright-or-dark#1]
it has to be made sure that for very narrow images that the code works..so the count percentage has to made dynamic i guess

**Comment by imneonizer** [comment]
Indeed it is dynamic, the row and column count always remain 1 less than the original image height and width.
More over no matter what size you provide the program always tries to resize the image to a particular width maintaining he aspect ratio
So chances of row count getting zero has been handeld very carefully.
Try to run the code and let me know if any issus still persists
